<?xml version="1.0" encoding="utf-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:macro name="wheel" params="mecanum side wheel_radius">

    <xacro:property name="wheel_separation_x" value="0.170" />

    <xacro:if value="${mecanum}">
      <xacro:property name="wheel_file" value="mecanum" />
      <xacro:property name="wheel_thickness" value="0.05" />
      <xacro:property name="mass" value="0.4" />

      <xacro:property name="ixx" value="0.0003145" />
      <xacro:property name="iyy" value="0.0004561" />
      <xacro:property name="izz" value="0.0003145" />

      <xacro:property name="wheel_separation_y" value="0.270" />
    </xacro:if>

    <xacro:unless value="${mecanum}">
      <xacro:property name="wheel_file" value="wheel" />
      <xacro:property name="wheel_thickness" value="0.036" />
      <xacro:property name="mass" value="0.051" />

      <xacro:property name="ixx" value="0.000050587413" />
      <xacro:property name="iyy" value="0.000085933192" />
      <xacro:property name="izz" value="0.000050587829" />

      <xacro:property name="wheel_separation_y" value="0.248" />
    </xacro:unless>

    <xacro:if value="${side == 'fl'}">
      <xacro:property name="x" value="${wheel_separation_x/2}" />
      <xacro:property name="y" value="${wheel_separation_y/2}" />
      <xacro:property name="mesh" value="package://robot_description/meshes/robot_xl/${wheel_file}_b.dae" />
      <xacro:property name="visual_rotation" value="${pi}" />
      <xacro:property name="fdir" value="1 -1 0" />
      <xacro:property name="joint_name" value="front_left_wheel_joint" />
      <xacro:property name="link_name" value="fl_wheel_link" />
    </xacro:if>
    <xacro:if value="${side == 'fr'}">
      <xacro:property name="x" value="${wheel_separation_x/2}" />
      <xacro:property name="y" value="${-wheel_separation_y/2}" />
      <xacro:property name="mesh" value="package://robot_description/meshes/robot_xl/${wheel_file}_a.dae" />
      <xacro:property name="visual_rotation" value="${pi}" />
      <xacro:property name="fdir" value="1 1 0" />
      <xacro:property name="joint_name" value="front_right_wheel_joint" />
      <xacro:property name="link_name" value="fr_wheel_link" />
    </xacro:if>
    <xacro:if value="${side == 'rl'}">
      <xacro:property name="x" value="${-wheel_separation_x/2}" />
      <xacro:property name="y" value="${wheel_separation_y/2}" />
      <xacro:property name="mesh" value="package://robot_description/meshes/robot_xl/${wheel_file}_a.dae" />
      <xacro:property name="visual_rotation" value="${0.0}" />
      <xacro:property name="fdir" value="1 1 0" />
      <xacro:property name="joint_name" value="rear_left_wheel_joint" />
      <xacro:property name="link_name" value="rl_wheel_link" />
    </xacro:if>
    <xacro:if value="${side == 'rr'}">
      <xacro:property name="x" value="${-wheel_separation_x/2}" />
      <xacro:property name="y" value="${-wheel_separation_y/2}" />
      <xacro:property name="mesh" value="package://robot_description/meshes/robot_xl/${wheel_file}_b.dae" />
      <xacro:property name="visual_rotation" value="${0.0}" />
      <xacro:property name="fdir" value="1 -1 0" />
      <xacro:property name="joint_name" value="rear_right_wheel_joint" />
      <xacro:property name="link_name" value="rr_wheel_link" />
    </xacro:if>

    <joint name="${joint_name}" type="continuous">
      <parent link="body_link" />
      <child link="${link_name}" />
      <origin xyz="${x} ${y} 0.0" rpy="0.0 0.0 0.0" />
      <axis xyz="0.0 1.0 0.0" />
      <limit effort="1.5" velocity="30.0" />
      <dynamics damping="0.001" friction="0.001" />
    </joint>

    <link name="${link_name}">
      <visual>
        <geometry>
          <mesh filename="${mesh}" scale="1 1 1" />
        </geometry>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 ${visual_rotation}" />
      </visual>

      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_thickness}" />
        </geometry>
        <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0" />
      </collision>

      <inertial>
        <mass value="${mass}" />
        <inertia ixx="${ixx}" ixy="0.0" ixz="0.0" iyy="${iyy}" iyz="0.0" izz="${izz}" />
      </inertial>
    </link>

    <gazebo reference="${link_name}"
      xmlns:ignition="http://ignitionrobotics.org/schema">
      <xacro:unless value="${mecanum}">
        <collision>
          <surface>
            <friction>
              <ode>
                <mu>1</mu>
                <mu2>1</mu2>
                <slip1>0.035</slip1>
                <slip2>0</slip2>
                <fdir1>0 0 1</fdir1>
              </ode>
            </friction>
          </surface>
        </collision>
      </xacro:unless>

      <xacro:if value="${mecanum}">
        <collision>
          <surface>
            <friction>
              <ode>
                <mu>0.8</mu>
                <mu2>0.2</mu2>
                <slip1>0.035</slip1>
                <slip2>0</slip2>
                <fdir1 ignition:expressed_in="base_link">${fdir}</fdir1>
              </ode>
            </friction>
          </surface>
        </collision>
      </xacro:if>
    </gazebo>

  </xacro:macro>
</robot>
